device: cuda
data:
  data_dir: /mnt/ceph_rbd/deepcam/mini/deepcam-data-n512
  global_batch_size: 32
  local_batch_size: 0
  gradient_accumulation_freq: 8
  shuffle: true
  n_epochs: 10
  prefetch: 4
opt:
  name: Adam
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.0001
lr_schedule:
  type: cosine_annealing
  base_lr: 0.001
  lr_warmup_steps: 400
  lr_warmup_factor: 1
  milestones: 800
  decay_rate: 0.1
  t_max: 10000
  eta_min: 0
training:
  target_iou: 0.82
  amp: True