device: cpu

data:
    data_dir: /work/z043//shared/imagenet-1k/huggingface/data
    global_batch_size: 32
    local_batch_size: 1 # change to 0 to use global_batch_size
    train_subset: 2048
    val_subset: 512
    gradient_accumulation_freq: 1
    drop_last_batch: True
    shuffle: True
    n_epochs: 10
    prefetch: 32

opt:
    name: SGD
    momentum: 0.9
    weight_decay: 0.0001

lr_schedule:
    base_lr: 0.002
    end_lr: 0.0001
    decay_steps: 5
    poly_power: 2 

training:
    target_accuracy: 0.759
    benchmark: True
